
obj-y				+= clk/
obj-y				+= clocksource/
obj-y				+= power/
obj-y				+= net/
obj-$(CONFIG_MFD_CORE)		+= mfd/
obj-$(CONFIG_MTD)		+= mtd/
obj-y				+= i2c/
obj-$(CONFIG_PWM_LOTUS)         += pwm/
obj-y				+= spi/
obj-y				+= mmc/
obj-y				+= usb/
obj-$(CONFIG_EDMAC)		+= dma/
obj-y				+= rtc/
