/*
 * Copyright (c) XMEDIA. All rights reserved.
 */

#ifndef XMEDIA_INTF_COMMON_H
#define XMEDIA_INTF_COMMON_H

#include "xmedia_type.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_RAW_8BIT = 0,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_RAW_10BIT,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_RAW_12BIT,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_RAW_14BIT,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_RAW_16BIT,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_RAW_20BIT,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_RAW_24BIT,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_YUV420_8BIT,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_YUV420_LEGACY_8BIT,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_YUV422_8BIT,
    XMEDIA_INTF_MIPI_CSI_DATA_TYPE_MAX
} xmedia_intf_mipi_csi_data_type;

typedef enum {
    XMEDIA_INTF_MIPI_DSI_DATA_TYPE_YUV422_16BIT = 0,
    XMEDIA_INTF_MIPI_DSI_DATA_TYPE_RGB666_18BIT,
    XMEDIA_INTF_MIPI_DSI_DATA_TYPE_RGB888_24BIT,
    XMEDIA_INTF_MIPI_DSI_DATA_TYPE_MAX
} xmedia_intf_mipi_dsi_data_type;

typedef enum {
    XMEDIA_INTF_BT_DATA_TYPE_YUV422_8BIT = 0,
    XMEDIA_INTF_BT_DATA_TYPE_YUV422_10BIT,
    XMEDIA_INTF_BT_DATA_TYPE_MAX
} xmedia_intf_bt_data_type;

typedef enum {
    XMEDIA_INTF_LCD_DATA_TYPE_RGB565_16BIT = 0,
    XMEDIA_INTF_LCD_DATA_TYPE_RGB666_18BIT,
    XMEDIA_INTF_LCD_DATA_TYPE_RGB888_24BIT,
    XMEDIA_INTF_LCD_DATA_TYPE_MAX
} xmedia_intf_lcd_data_type;

typedef enum {
    XMEDIA_INTF_LVDS_DATA_TYPE_RGB666_18BIT = 0,
    XMEDIA_INTF_LVDS_DATA_TYPE_RGB666_36BIT,
    XMEDIA_INTF_LVDS_DATA_TYPE_RGB888_24BIT,
    XMEDIA_INTF_LVDS_DATA_TYPE_RGB888_48BIT,
    XMEDIA_INTF_LVDS_DATA_TYPE_MAX
} xmedia_intf_lvds_data_type;

typedef enum {
    XMEDIA_INTF_DC_DATA_TYPE_RAW_8BIT = 0,
    XMEDIA_INTF_DC_DATA_TYPE_RAW_10BIT,
    XMEDIA_INTF_DC_DATA_TYPE_RAW_12BIT,
    XMEDIA_INTF_DC_DATA_TYPE_RAW_14BIT,
    XMEDIA_INTF_DC_DATA_TYPE_RAW_16BIT,
    XMEDIA_INTF_DC_DATA_TYPE_MAX
} xmedia_intf_dc_data_type;

typedef enum {
    XMEDIA_INTF_TYPE_BT601 = 0,
    XMEDIA_INTF_TYPE_BT656,
    XMEDIA_INTF_TYPE_BT1120,
    XMEDIA_INTF_TYPE_MIPI_CSI,
    XMEDIA_INTF_TYPE_MIPI_DSI,
    XMEDIA_INTF_TYPE_LCD,
    XMEDIA_INTF_TYPE_LVDS,
    XMEDIA_INTF_TYPE_DC,
    XMEDIA_INTF_TYPE_MCU,
    XMEDIA_INTF_TYPE_SPI,
    XMEDIA_INTF_TYPE_MAX
} xmedia_intf_type;

/* bt601&bt656 */
typedef enum {
    XMEDIA_INTF_BT601_BT656_DATA_SEQ_UYVY = 0,
    XMEDIA_INTF_BT601_BT656_DATA_SEQ_VYUY,
    XMEDIA_INTF_BT601_BT656_DATA_SEQ_YUYV,
    XMEDIA_INTF_BT601_BT656_DATA_SEQ_YVYU,
    XMEDIA_INTF_BT601_BT656_DATA_SEQ_MAX
} xmedia_intf_bt601_bt656_data_seq;

typedef enum {
    XMEDIA_INTF_BT1120_DATA_SEQ_VUVU = 0,
    XMEDIA_INTF_BT1120_DATA_SEQ_UVUV,
    XMEDIA_INTF_BT1120_DATA_SEQ_MAX,
} xmedia_intf_bt1120_data_seq;

typedef enum {
    XMEDIA_INTF_YUV_DATA_SEQ_UYVY = 0,
    XMEDIA_INTF_YUV_DATA_SEQ_VYUY,
    XMEDIA_INTF_YUV_DATA_SEQ_YUYV,
    XMEDIA_INTF_YUV_DATA_SEQ_YVYU,
    XMEDIA_INTF_YUV_DATA_SEQ_MAX
} xmedia_intf_yuv_data_seq;

typedef enum {
    XMEDIA_INTF_LCD_DATA_SEQ_RGB = 0,
    XMEDIA_INTF_LCD_DATA_SEQ_RBG,
    XMEDIA_INTF_LCD_DATA_SEQ_GRB,
    XMEDIA_INTF_LCD_DATA_SEQ_GBR,
    XMEDIA_INTF_LCD_DATA_SEQ_BRG,
    XMEDIA_INTF_LCD_DATA_SEQ_BGR,
    XMEDIA_INTF_LCD_DATA_SEQ_MAX,
} xmedia_intf_lcd_data_seq;

typedef enum {
    XMEDIA_INTF_LVDS_FORMAT_VESA = 0,
    XMEDIA_INTF_LVDS_FORMAT_JEIDA,
    XMEDIA_INTF_LVDS_FORMAT_MAX
} xmedia_intf_lvds_format;

#ifdef __cplusplus
}
#endif

#endif


