#
# Automatically generated file; DO NOT EDIT.
# xmedia SDK Configuration
#

#
# Base
#
# CONFIG_XM7206V11A is not set
# CONFIG_XM7206V10 is not set
# CONFIG_XM7206V10B is not set
CONFIG_XM7206V12A=y
# CONFIG_XM7206V11 is not set
# CONFIG_XM7206V11AT is not set
CONFIG_XMEDIA_CHIP_TYPE=xm7206v12a
CONFIG_XMEDIA_CHIP_ARCH=xmorca

#
# Toolchains Config
#
# CONFIG_XMEDIA_KERNEL_ARM_GCC12_2_0_LINUX is not set
# CONFIG_XMEDIA_KERNEL_AARCH64_GCC12_2_0_LINUX is not set
CONFIG_XMEDIA_KERNEL_ARM_GCC12_2_0_UCLIBC_LINUX=y
CONFIG_XMEDIA_KERNEL_ARM_TOOLCHAINS=arm-gcc12.2.0-linux-uclibceabi
CONFIG_XMEDIA_CPU_ARCH=arm
# CONFIG_XMEDIA_USR_ARM_GCC12_2_0_LINUX is not set
CONFIG_XMEDIA_USR_ARM_GCC12_2_0_UCLIBC_LINUX=y
CONFIG_XMEDIA_USR_ARM_TOOLCHAINS=arm-gcc12.2.0-linux-uclibceabi
CONFIG_XMEDIA_SDK_MODE_LOG=y
# CONFIG_XMEDIA_SDK_MODE_NOLOG is not set
CONFIG_XMEDIA_SDK_LOG_MODE=log
# CONFIG_XMEDIA_QUICK_START is not set

#
# Board
#

#
# Flash Config
#
CONFIG_XMEDIA_NAND_FLASH_SUPPORT=y

#
# Nand Flash device support
#
# CONFIG_XMEDIA_NAND_SUPPORT is not set
CONFIG_XMEDIA_SPI_NAND_SUPPORT=y
CONFIG_XMEDIA_SPI_SUPPORT=y
CONFIG_XMEDIA_SPI_BLOCK_SIZE=64k
CONFIG_XMEDIA_EMMC_SUPPORT=y

#
# Boot Regfile Config
#
CONFIG_XMEDIA_BOOT_REG_NAME=XM7206V12A_EVB_6L_DDR3_2133M_256M_1x16bit

#
# Bootloader System
#
CONFIG_XMEDIA_UBOOT_SUPPORT=y
CONFIG_XMEDIA_UBOOT_SUPPORT_2020_01=y
CONFIG_XMEDIA_UBOOT_VER=u-boot-2020.01
CONFIG_XMEDIA_BOOT_DEFCONFIG=xmorca_defconfig
CONFIG_XMEDIA_BOOT_ENV_STARTADDR=0x80000
CONFIG_XMEDIA_BOOT_ENV_SIZE=0x10000
CONFIG_XMEDIA_DDR_TRAINING_SUPPORT=y
CONFIG_XMEDIA_BOOT_APP_SUPPORT=y

#
# Linux System
#

#
# Kernel
#
CONFIG_XMEDIA_LINUX_5_10_Y=y
# CONFIG_XMEDIA_LINUX_4_9_Y is not set
CONFIG_XMEDIA_KERNEL_VERSION=linux-5.10.y
CONFIG_XMEDIA_KERNEL_SUPPORT_SMP=y
CONFIG_XMEDIA_KERNEL_DEFCONFIG=xmorca_defconfig
# CONFIG_XMEDIA_GMP_BUILDIN is not set

#
# InitRamdisk Config
#
CONFIG_XMEDIA_TOYBOX_CFG_NAME=toybox-0.8.8

#
# Filesystem
#
CONFIG_XMEDIA_BUSYBOX_CFG_NAME=busybox-1.36.1
CONFIG_XMEDIA_LIBCPP_SUPPORT=y
CONFIG_XMEDIA_ROOTFS_STRIP=y
CONFIG_XMEDIA_ROOTFS_YAFFS=y
CONFIG_XMEDIA_ROOTFS_JFFS2=y
# CONFIG_XMEDIA_ROOTFS_SQUASHFS is not set
CONFIG_XMEDIA_ROOTFS_EXT4=y
CONFIG_XMEDIA_EMMC_ROOTFS_SIZE=32
CONFIG_XMEDIA_ROOTFS_UBIIMG=y
CONFIG_XMEDIA_UBI_PARTITION_SIZE=64M

#
# Tools
#
# CONFIG_XMEDIA_UDEV_SUPPORT is not set
# CONFIG_XMEDIA_DOSFS_SUPPORT is not set
# CONFIG_XMEDIA_E2FSPROGS_SUPPORT is not set
# CONFIG_XMEDIA_GDB_SUPPORT is not set
# CONFIG_XMEDIA_MTDUTILS_SUPPORT is not set
CONFIG_XMEDIA_REG_SUPPORT=y
# CONFIG_XMEDIA_MIITOOLS_SUPPORT is not set
# CONFIG_XMEDIA_CANTOOLS_SUPPORT is not set
