
obj-$(CONFIG_CMD_HW_GUNZIP) += cmd_hw_gunzip.o

obj-$(if $(CONFIG_LOTUS_DISABLE_DOWNLOAD),,y) += download_process.o
obj-y += getinfo.o
obj-y += misc.o

obj-$(CONFIG_EXT4_SPARSE) += unsparse.o
obj-y += shutdown.o
obj-$(CONFIG_QS_MCU) += mcu.o

