#!/bin/sh

#Load modules in /lib/modules
modules_list=$(echo $(find /lib/modules/$(uname -r)/ -name *.ko))
for mod in ${modules_list}; do
	echo "Load $mod"
	modprobe $(basename $mod)
done

mknod /dev/console c 5 1
mknod /dev/ttyAMA0 c 204 64
mknod /dev/ttyAMA1 c 204 65
mknod /dev/ttyS000 c 204 64
mknod /dev/null	   c 1 3


