#
# this is a test config para file.
# !!! This parameters only use to test!!!
#
[basic]
# 工作采样率 8000 or 16000，默认：8000
sampleRate = 16000
# 输入声道数[1,2] 1 for vqe v1, 2 for vqe v2
inchnnum = 2
# 输出声道数
outchnnum = 2
# 数据帧长 10ms：160(8k)、 320(16k)
frameSample = 160
# AI/AO Buffer帧数
frameNums = 30
# vqe 算法版本 16: vqe detect v1
vqe_version = 16

[volume]
# 麦克风Codec输入增益 范围：[-95~48]
codec_input_vol = 20
# AI后级Vqe音量 范围：[-81~18]，默认：0
vqe_ai_vol = 0
# AO 后级vqe音量 范围：[-81~18]，默认：0
vqe_ao_vol = 0

#目前bcd只支持sampleRate = 16000
[BCD]
# 使能模块 0: disable，1: enable
enable = 0
# 模式选择 0:自动模式，1: 用户模式，2:高级模式
usr_mode = 1
# 哭声概率，范围: [0, 100]
alarm_threshold = 80
# 冻结时间，范围: [0s, 120s]
time_limit = 5
# 激活次数，范围: [1, 5]
time_limit_threshold_count = 3
# 退出冻结噪声时间，范围: [0, 120]
interval_time = 3

#目前GBD只支持sampleRate = 8000
[GBD]
# 使能模块 0: disable，1: enable
enable = 0
# 模式选择 0:自动模式，1: 用户模式，2:高级模式
usr_mode = 1
# 哭声概率，范围: [0, 100]
alarm_threshold = 80
# 冻结时间，范围: [0s, 120s]
time_limit = 5
# 激活次数，范围: [1, 5]
time_limit_threshold_count = 1
# 退出冻结噪声时间，范围: [0, 120]
interval_time = 3

[SSL]
# 使能模块 0: disable，1: enable，目前只支持2ch。inchnnum，outchnnum需要配置为2
enable = 1
# 麦克风间距,范围: [30mm, 150mm]
mic_distance = 100
# 灵敏度，范围：[0, 9]
sensitivity_level = 5
# 0表示线阵, 1表示环阵
shape = 0

[VED]
# 使能模块 0: disable，1: enable
enable = 0
# 模式选择 0:自动模式，1: 用户模式，2:高级模式
mode = 1
# 音量阈值，范围: [-80, 0]
volume_threshold = 0
# 突变使能检测使能标志，0：不使能，1：使能
mutation_flag = 0
# 快速突变阈值，范围: [10db, 80db]
fast_change_threshold = 10
# 平稳突变阈值，范围: [1db, 20db]
slow_change_threshold = 2

[HPF]
# 使能模块 0: disable，1: enable
enable = 0
# 模式选择 0--自动模式 1--用户模式
mode = 1
# 高通滤波截至频率 范围：[80/120/150]
freq = 80
