#
# this is a test config para file.
# !!! This parameters only use to test!!!
#
[basic]
# 工作采样率 8000 or 16000，默认：8000
sampleRate = 16000
# 输入声道数[1,2] 1 for vqe v1, 2 for vqe v2
inchnnum = 1
# 输出声道数
outchnnum = 1
# 数据帧长 10ms
frameSample = 160
# AI/AO Buffer帧数
frameNums = 30
# vqe 算法版本 [1~n]  1: vqe v1 2: vqe v2
vqe_version = 1

[volume]
# 麦克风Codec输入增益 范围：[-95~48]
codec_input_vol = 20
# AI后级Vqe音量 范围：[-81~18]，默认：0
vqe_ai_vol = 0
# AO 后级vqe音量 范围：[-81~18]，默认：0
vqe_ao_vol = 0

[ANR]
# 使能模块 0: disable，1: enable
enable = 1
# 模式选择 0:自动模式，1: 用户模式，2:高级模式
mode = 1
# 用户场景，0：正常场景，1：音乐场景
usr_scene = 0
# 降噪模式，0：语音模式，偏向于保语音，1：降噪模式，偏向于降噪
nr_mode = 0
# 最大噪声压制增益，范围: [5, 40]
max_suppress_gain = 6
# 平稳噪声降噪等级，范围: [0, 9]
suppress_level = 2
# 非平稳噪声降噪等级，范围 : [0, 9]
nonstationary_suppress_level = 0

[AGC]
# 使能模块 0: disable，1: enable
enable = 1
# 模式选择 0:自动模式，1: 用户模式，2:高级模式
mode = 1
# 目标电平 范围：[-20, -1]，默认：-6
target_level = -6
# 最大增益 范围：[0, 30]，默认：20
max_boost_gain = 20
# 噪声底线 范围：[-120, -25]，默认：-100
noise_floor = -100
# 调整速度 范围：[1, 100]，默认：8
attack_time = 8
# 释放速度 范围：[1, 100]，默认：20
release_time = 20
# 噪声压制比率，范围: [1, 100], 默认：12
ratio = 12

[AEC]
# 使能模块 0: disable，1: enable
enable = 1
# 模式选择 0:自动模式，1: 用户模式，2:高级模式
mode = 1
# 舒适噪声开关, 0 : disable 1 : enable
cng_enable = 1
# 高低频分频点, range : [1500, 3800]
freq_boundary = 1800
# 低频回声消除等级,  range : [0, 9]
low_suppress_level = 7
# 高频回声消除等级,  range : [0, 9]
high_suppress_level = 5
# 低频语音保护等级,  range : [0, 9]
low_enhance_voice_protect_level = 0
# 高频语音保护等级,  range : [0, 9]
high_enhance_voice_protect_level = 0

[DEREVERB]
# 使能模块 0: disable，1: enable
enable = 0
# 模式选择 0:自动模式，1: 用户模式，2:高级模式
mode = 1
# 去混响延时，范围：[5, 30]
delay_offset = 6
# 去混响延时偏移个数，范围：[3, 10]
delay_count = 3

[VAD]
# 使能模块 0: disable，1: enable
enable = 0
# 模式选择 0:自动模式，1: 用户模式，2:高级模式
mode = 1
# 语音检测灵敏度，范围：[0, 9]
sensitivity_level = 6

[WNS]
# 使能模块 0: disable，1: enable
enable = 0
# 模式选择 0:自动模式，1: 用户模式，2:高级模式
mode = 1
# 降风噪等级，范围：[0, 4]
suppress_level = 4

[HPF]
# 使能模块 0: disable，1: enable
enable = 1
# 模式选择 0--自动模式 1--用户模式
mode = 1
# 高通滤波截至频率 范围：[80/120/150]
freq = 80

[EQ]
# 使能模块 0: disable，1: enable
enable = 1
# EQ 频段调节，范围：[-50~20]
# 分别对应频率点：60, 100, 150, 200, 250, 350, 500, 800, 1.2k, 1.6k, 2k,
#                 2.4k, 2.5k, 2.8k, 3.1k, 3.4k, 3.6k, 3.8k, 3.9k, 4k,
#                 4.5k, 5k, 5.5k, 6k, 6.5k, 7k, 7.3k, 7.6k, 7.8k, 8k,
# 其中，4.5k以上频率点只有在采样率为16k才生效
# Freq: 60Hz
gain_0 = 0
# Freq: 100Hz
gain_1 = 0
# Freq: 150Hz
gain_2 = 0
# Freq: 200Hz
gain_3 = 0
# Freq: 250Hz
gain_4 = 0
# Freq: 350Hz
gain_5 = 0
# Freq: 500Hz
gain_6 = 0
# Freq: 800Hz
gain_7 = 0
# Freq: 1200Hz
gain_8 = 0
# Freq: 1600Hz
gain_9 = 0
# Freq: 2000Hz
gain_10 = 0
# Freq: 2400Hz
gain_11 = 0
# Freq: 2500Hz
gain_12 = 0
# Freq: 2800Hz
gain_13 = 0
# Freq: 3100Hz
gain_14 = 0
# Freq: 3400Hz
gain_15 = 0
# Freq: 3600Hz
gain_16 = 0
# Freq: 3800Hz
gain_17 = 0
# Freq: 3900Hz
gain_18 = 0
# Freq: 4000Hz
gain_19 = 0
# Freq: 4500Hz
gain_20 = 0
# Freq: 5000Hz
gain_21 = 0
# Freq: 5500Hz
gain_22 = 0
# Freq: 6000Hz
gain_23 = 0
# Freq: 6500Hz
gain_24 = 0
# Freq: 7000Hz
gain_25 = 0
# Freq: 7300Hz
gain_26 = 0
# Freq: 7600Hz
gain_27 = 0
# Freq: 7800Hz
gain_28 = 0
# Freq: 8000Hz
gain_29 = 0
