
ccflags-y += -I$(srctree)/product/update
ccflags-y += -I$(srctree)/lotus/misc

obj-$(CONFIG_CMD_SF) += au_spinor_flash.o
obj-$(CONFIG_CMD_NAND) += au_nand_flash.o
obj-$(CONFIG_SUPPORT_EMMC_BOOT) += au_emmc_flash.o
