
UBSAN_SANITIZE := y

ccflags-y += -Wall -Werror
subdir-ccflags-y += -Wall -Werror

obj-y += drivers/

obj-y += atags/
obj-y += misc/
obj-y += timestamp/
obj-y += machine/
obj-y += flash_stats/
obj-y += fs/
obj-$(CONFIG_LOTUS_SELF_TEST) += self-test/
