# SPDX-License-Identifier: GPL-2.0
# Copyright (c) LOTUS. All rights reserved.


# obj-$(CONFIG_LOTUS_PHY) += icplus_phy.o
# obj-$(CONFIG_LOTUS_PHY) += jlsemi_phy.o
obj-$(CONFIG_LOTUS_PHY) += ephy_phy.o
