obj-$(CONFIG_DMA_CMA)			+= cma/
obj-$(CONFIG_TIMER_XMEDIA_SP804)	+= timer/
obj-y += timestamp/
obj-y += misc/
obj-y += atags/
obj-$(CONFIG_ARCH_XMEDIA) += soc/xm720xxx/
obj-$(CONFIG_HPFAT_SUPPORT) += hpfat/
